export const ROOM_LIST_REQUEST = 'ROOM_LIST_REQUEST'
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS'
export const ROOM_LIST_FAIL = 'ROOM_LIST_FAIL'

export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST'
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'

export const ROOM_DELETE_REQUEST = 'ROOM_DELETE_REQUEST'
export const ROOM_DELETE_SUCCESS = 'ROOM_DELETE_SUCCESS'
export const ROOM_DELETE_FAIL = 'ROOM_DELETE_FAIL'

export const ROOM_CREATE_REQUEST = 'ROOM_CREATE_REQUEST'
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS'
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL'
export const ROOM_CREATE_RESET = 'ROOM_CREATE_RESET'

export const ROOM_UPDATE_REQUEST = 'ROOM_UPDATE_REQUEST'
export const ROOM_UPDATE_SUCCESS = 'ROOM_UPDATE_SUCCESS'
export const ROOM_UPDATE_FAIL = 'ROOM_UPDATE_FAIL'
export const ROOM_UPDATE_RESET = 'ROOM_UPDATE_RESET'

export const ROOM_CREATE_REVIEW_REQUEST = 'ROOM_CREATE_REVIEW_REQUEST'
export const ROOM_CREATE_REVIEW_SUCCESS = 'ROOM_CREATE_REVIEW_SUCCESS'
export const ROOM_CREATE_REVIEW_FAIL = 'ROOM_CREATE_REVIEW_FAIL'
export const ROOM_CREATE_REVIEW_RESET = 'ROOM_CREATE_REVIEW_RESET'

export const ROOM_TOP_REQUEST = 'ROOM_TOP_REQUEST'
export const ROOM_TOP_SUCCESS = 'ROOM_TOP_SUCCESS'
export const ROOM_TOP_FAIL = 'ROOM_TOP_FAIL'
